Yovo/Controllers/HousesController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Yovo.Models;
using Yovo.Viewmodel;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Web;
using System.Data.SqlClient;

namespace Yovo.Controllers
{
    public class HousesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Houses
        public ActionResult Index()
        {
            ViewBag.Owners = db.Users.Where(u => u.Roles.ToString() == "Owner");
            var x = db.Houses.Include(h => h.Owner).ToList();
            return View(db.Houses.Include(h => h.Owner));
        }



        [HttpGet]
        public ActionResult SearchResults(string region, string city, decimal? price, decimal? SquareMeters)
        {
            SearchVM src = new SearchVM();
            var userid = User.Identity.GetUserId();
            var query = db.Addresses.Include(adr => adr.House).Include(adr => adr.House.Owner).Where(adr => adr.House.Owner.Id != userid);
            var x = query.ToList();
            if (region != "0"){query = query.Where(adr => adr.Region == region);}

            if (city != "0"){query = query.Where(adr => adr.Country == city);}

            if (price != null){query = query.Where(adr => adr.House.Price == price);}

            if (SquareMeters != null){query = query.Where(adr => adr.House.SquareMeters == SquareMeters);}
                       
            src.Address = query.ToList();
            src.HouseImg = db.HouseImgs.ToList();
            return View(src);
        }


        // GET: Houses
        public ActionResult MyHouses()
        {
            var CurrentUser = User.Identity.GetUserId();
            var houses = new SearchVM();
            houses.House = db.Houses.Include(h => h.Features).Where(h => h.Owner.Id == CurrentUser).ToList();
            houses.HouseImg = db.HouseImgs.ToList();
            //var CurrentUserId = ac.UserManager.FindById(User.Identity.GetUserId());
            return View(houses);
        }

        // GET: Houses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // Because it is an array of bits we need to instantiate it before to save it.
            HouseSpecsViewModel house = new HouseSpecsViewModel();
            house.House = db.Houses.Include(h => h.Owner).Include(h => h.Features).SingleOrDefault(h => h.Id == id);
            house.Address = db.Addresses.SingleOrDefault(a => a.HouseId == id);
            house.HouseImg = db.HouseImgs.SingleOrDefault(i => i.HouseId == id);

            ViewBag.UserId = User.Identity.GetUserId();
            if (house == null)
            {
                return HttpNotFound();
            }
            var x = house;
            return View(house);
        }

        // GET: Houses/Create
        public ActionResult Create()
        {
            HouseSpecsViewModel h = new HouseSpecsViewModel();
            h.Features = db.Features.ToList();
            h.HouseImg = new HouseImg();
            return View(h);
        }

        // POST: Houses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HouseSpecsViewModel model, HttpPostedFileBase image1)
        {
            var x = image1;
            if (ModelState.IsValid)
            {
                var y = Request.Files[0];
                House house = model.House;
                Address address = model.Address;
                foreach (var item in model.Features)
                {
                    if (item.IsChecked)
                    {
                        house.Features.Add(db.Features.Find(item.Id));
                        item.IsChecked = false;
                    }
                }
                if (image1 != null)
                {
                    model.HouseImg = new HouseImg();
                    model.HouseImg.Image = new byte[image1.ContentLength];
                    image1.InputStream.Read(model.HouseImg.Image, 0, image1.ContentLength);
                    model.HouseImg.HouseId = model.House.Id;
                    db.HouseImgs.Add(model.HouseImg);
                }

                house.Owner = db.Users.Find(User.Identity.GetUserId());
                address.HouseId = house.Id;
                db.Houses.Add(house);
                db.Addresses.Add(address);
                db.SaveChanges();
              

                var ctrl = new AccountController();
                ctrl.ControllerContext = ControllerContext;
                var test = User.Identity.GetUserId();
                ctrl.UserManager.RemoveFromRole(User.Identity.GetUserId(), "Renter");
                ctrl.UserManager.AddToRole(User.Identity.GetUserId(), "Owner");
                return RedirectToAction("Index");
            }

            return RedirectToAction("Details", new { id = model.House.Id});
        }

        // GET: Houses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            House house = db.Houses.Find(id);
            if (house == null)
            {
                return HttpNotFound();
            }
            return View(house);
        }

        // POST: Houses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Description,Rooms,Visitors,SquareMeters,Price,UserId")] House house)
        {
            if (ModelState.IsValid)
            {
                db.Entry(house).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(house);
        }

        // GET: Houses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            House house = db.Houses.Find(id);
            if (house == null)
            {
                return HttpNotFound();
            }
            return View(house);
        }

        // POST: Houses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            House house = db.Houses.Find(id);
            db.Houses.Remove(house);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Yovo/Controllers/ReservationsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Yovo.Models;
using Yovo.Viewmodel;
using Newtonsoft.Json;
using System.Web.Script.Serialization;

namespace Yovo.Controllers
{
    public class ReservationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Reservations
        public ActionResult Index()
        {
            var reservations = db.Reservations.Include(r => r.House);
            return View(reservations.ToList());
        }

        // GET: Reservations
        public ActionResult MyReservations()
        {
            ViewBag.UserId = User.Identity.GetUserId();
            var userId = User.Identity.GetUserId();
            var reservations = db.Reservations.Include(r => r.Renter).Include(r => r.House).Include(r => r.House.Owner).Where(r => r.UserId == userId).ToList();
            return View(reservations);
        }

        // GET: Reservations
        public ActionResult HouseReservations(int? id)
        {
            ViewBag.House = db.Houses.FirstOrDefault(h => h.Id == id);
            var reservations = db.Reservations.Include(r => r.House).Include(r => r.Renter).Where(r => r.HouseId == id).ToList();
            return View(reservations);
        }

        // GET: Reservations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // GET: Reservations/Availability
        public ActionResult availability(int houseId)
        {
            ViewBag.House = db.Houses.Find(houseId);
            return View();
        }

        public JsonResult HidJson(int houseId)
        {
            ReservationCheckVM oldReservation = new ReservationCheckVM();
            oldReservation.OldReservations = db.Reservations.Where(r => r.HouseId == houseId).ToList();
            var x = Json(oldReservation.OldReservations, JsonRequestBehavior.AllowGet);
            return Json(oldReservation.OldReservations,JsonRequestBehavior.AllowGet);
        }

        // POST: Reservations/Availability
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Availability(ReservationCheckVM res)
        {
            ViewBag.House = TempData["House"];
            var x = (ModelState.IsValid);
            if (ModelState.IsValid)
            {
                res.NewReservation.BookingDate = DateTime.Now;
                res.NewReservation.HouseId = ViewBag.House.Id;
                res.NewReservation.UserId = User.Identity.GetUserId();
                db.Reservations.Add(res.NewReservation);
                db.SaveChanges();
                return RedirectToAction("MyHouses", "Houses");
            }
            int houseid = ViewBag.House.Id;
            res.OldReservations = db.Reservations.Where(r => r.HouseId == houseid).ToList();
            ViewBag.HouseId = new SelectList(db.Houses, "Id", "Title", ViewBag.House.Id);
            return View(res);
        }

        // GET: Reservations/Book
        [Authorize]
        public ActionResult Book(int houseId)
        {
            ViewBag.House = db.Houses.Find(houseId);
            return View();
        }

        // POST: Reservations/Book
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Book(ReservationCheckVM res)
        {
            ViewBag.House = TempData["House"];
            var x = (ModelState.IsValid);
                if (ModelState.IsValid)
                {
                    res.NewReservation.BookingDate = DateTime.Now;
                    res.NewReservation.Occupancy = db.Houses.Find(ViewBag.House.Id).Visitors;
                    res.NewReservation.Price = db.Houses.Find(ViewBag.House.Id).Price;
                    res.NewReservation.HouseId = ViewBag.House.Id;
                    res.NewReservation.UserId = User.Identity.GetUserId();
                    res.NewReservation.Renter = db.Users.Find(User.Identity.GetUserId());
                    db.Reservations.Add(res.NewReservation);
                    db.SaveChanges();
                    return RedirectToAction("ThankYou");
                }
                
            int houseid = ViewBag.House.Id;
            res.OldReservations = db.Reservations.Where(r => r.HouseId == houseid).ToList();
            ViewBag.HouseId = new SelectList(db.Houses, "Id", "Title", ViewBag.House.Id);
            return View(res);
        }
        public ActionResult ThankYou()
        {
            return View();
        }

        // GET: Reservations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            ViewBag.HouseId = new SelectList(db.Houses, "Id", "Title", reservation.HouseId);
            return View(reservation);
        }

        // POST: Reservations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FromDate,ToDate,UserId,HouseId")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reservation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.HouseId = new SelectList(db.Houses, "Id", "Title", reservation.HouseId);
            return View(reservation);
        }

        // GET: Reservations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reservation reservation = db.Reservations.Find(id);
            db.Reservations.Remove(reservation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Yovo/Views/Houses/Create.cshtml
@model Yovo.Viewmodel.HouseSpecsViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!--Script for Bing Maps START-->
<!-- jQuery 2.2.4 -->
<script src="~/Scripts/jquery.min.js"></script>
<script type='text/javascript' src='http://www.bing.com/api/maps/mapcontrol?callback=GetMap&key=AjtUzWJBHlI3Ma_Ke6Qv2fGRXEs0ua5hUQi54ECwfXTiWsitll4AkETZDihjcfeI' async defer></script>
<!--Script for Bing Maps END-->

<h2>Create</h2>

@using (Html.BeginForm("Create", "Houses", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-6">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group col-xs-12 col-sm-6 col-md-12 col-lg-12">
                    @Html.LabelFor(model => model.House.Title, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-xs-12 col-sm-8 col-md-12 col-lg-12">
                        @Html.EditorFor(model => model.House.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.House.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-xs-12 col-sm-6 col-md-12 col-lg-12">
                    @Html.LabelFor(model => model.House.Description, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-xs-12 col-sm-8 col-md-12 col-lg-12">
                        @Html.EditorFor(model => model.House.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.House.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-xs-12 col-sm-6 col-md-12 col-lg-12">
                    @Html.LabelFor(model => model.House.Rooms, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-xs-12 col-sm-8 col-md-12 col-lg-12">
                        @Html.EditorFor(model => model.House.Rooms, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.House.Rooms, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-xs-12 col-sm-6 col-md-6 col-lg-12">
                    @Html.LabelFor(model => model.House.Visitors, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-12">
                        @Html.EditorFor(model => model.House.Visitors, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.House.Visitors, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-xs-12 col-sm-6 col-md-6 col-lg-12">
                    @Html.LabelFor(model => model.House.SquareMeters, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-12">
                        @Html.EditorFor(model => model.House.SquareMeters, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.House.SquareMeters, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-xs-12 col-sm-6 col-md-6 col-lg-12">
                    @Html.LabelFor(model => model.House.Price, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-12">
                        @Html.EditorFor(model => model.House.Price, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.House.Price, "", new { @class = "text-danger" })
                    </div>
                </div>
                <h5>Amenities</h5>
                <hr />

                <div class="col-md-12">
                    @Html.EditorFor(model => model.Features)
                </div>
                <h5>House Photo</h5>
                <div class="form-group col-md-12">

                    <input type="file" id="image1" name="image1" />
                </div>
                <hr />
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-outline-success waves-effect" />
                </div>

            </div>
        </div>
        <div class="col-md-6">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="form-group col-xs-12 col-sm-6 col-md-6 col-lg-12">
                    <div class="control-label col-md-4">City</div>
                    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-12">
                        @Html.EditorFor(model => model.Address.Country, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address.Country, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group col-xs-12 col-sm-6 col-md-6 col-lg-12">
                    @Html.LabelFor(model => model.Address.Region, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-12">
                        @Html.EditorFor(model => model.Address.Region, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address.Region, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group col-xs-12 col-sm-6 col-md-6 col-lg-12">
                    @Html.LabelFor(model => model.Address.Street, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-12">
                        @Html.EditorFor(model => model.Address.Street, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address.Street, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group col-xs-12 col-sm-6 col-md-6 col-lg-12">
                    @Html.LabelFor(model => model.Address.Latitude, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-12">
                        @Html.EditorFor(model => model.Address.Latitude, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address.Latitude, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group col-xs-12 col-sm-6 col-md-6 col-lg-12">
                    @Html.LabelFor(model => model.Address.Longitude, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-12">
                        @Html.EditorFor(model => model.Address.Longitude, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address.Longitude, "", new { @class = "text-danger" })
                        <input type="button" value="find me" class="btn btn-primary" onClick="geocode()" />
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-12 ">
                        <div id="myMap" style="position:relative;width:100%; height:300px;"></div>
                    </div>
                </div>

            </div>
        </div>
    </div>
}
@*@RenderPage("~/Views/Shared/_PartialPagePhotos.cshtml")*@
@* @Html.ActionLink("Back to List", "Index") *@


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}
<script>
    function GetMap() {
        var default_map;
        default_map = new Microsoft.Maps.Map('#myMap', {
            center: new Microsoft.Maps.Location(40.63640246266535, 22.944573389221176),
            zoom: 12
        });
    }
    var BingMapsKey = 'AjtUzWJBHlI3Ma_Ke6Qv2fGRXEs0ua5hUQi54ECwfXTiWsitll4AkETZDihjcfeI';
    var map;
    function geocode() {
        var street = document.getElementById('Address_Street').value;
        var region = document.getElementById('Address_Region').value;
        var city = document.getElementById('Address_Country').value;

        var geocodeRequest = "http://dev.virtualearth.net/REST/v1/Locations?query=" + encodeURIComponent(region) + "/" + encodeURIComponent(street) + "/" + encodeURIComponent(city) + "&key=" + BingMapsKey;

        CallRestService(geocodeRequest, GeocodeCallback);
    }

    function GeocodeCallback(response) {
        var output = document.getElementById('output');

        if (response && response.resourceSets && response.resourceSets.length > 0 && response.resourceSets[0].resources) {

            var results = response.resourceSets[0].resources;

            //--------------------------------------------------------
            map = new Microsoft.Maps.Map('#myMap', {
                center: new Microsoft.Maps.Location(results[0].point.coordinates[0], results[0].point.coordinates[1]),
                zoom: 18
            });
            var greenPin = new Microsoft.Maps.Pushpin(new Microsoft.Maps.Location(results[0].point.coordinates[0], results[0].point.coordinates[1]), { color: '#0f0', icon: 'offline_marker.png', draggable: true });
            map.entities.push(greenPin);
            Microsoft.Maps.Events.addHandler(greenPin, 'dragend', function (e) { highlight(e); });
            Microsoft.Maps.loadModule('Microsoft.Maps.AutoSuggest', function () {
                var manager = new Microsoft.Maps.AutosuggestManager({ map: map });
                manager.attachAutosuggest('#full', ".address", selectedSuggestion);
            });
            document.getElementById("Address_Latitude").value = results[0].point.coordinates[0];
            document.getElementById("Address_Longitude").value = results[0].point.coordinates[1];
            //--------------------------------------------------------

        } else {
            alert("No results found.");
        }
    }
    function highlight(event) {
        var coord;
        //var latitude;
        //Highlight the mouse event div to indicate that the event has fired.
        //document.getElementById(id).style.background = 'LightGreen';
        coord = event.target.getLocation().toString().replace(/[^0-9.,]+/g, "");
        var index = coord.indexOf(",");  // Gets the first index where a space occours
        var a = coord.substr(0, index);
        var b = coord.substr(index + 1);
        //longitude = coordinates.substr(1, index);
        document.getElementById("Address_Latitude").value = a;
        document.getElementById("Address_Longitude").value = b;
        setTimeout(function () { document.getElementById(id).style.background = 'white'; }, 1000);
    }
    function selectedSuggestion(result) {
        //Remove previously selected suggestions from the map.
        map.entities.clear();

        //Show the suggestion as a pushpin and center map over it.
        var pin = new Microsoft.Maps.Pushpin(result.location);
        map.entities.push(pin);
        map.setView({ bounds: result.bestView });
    }
    function CallRestService(request, callback) {
        $.ajax({
            url: request,
            dataType: "jsonp",
            jsonp: "jsonp",
            success: function (r) {
                callback(r);
            },
            error: function (e) {
                alert(e.statusText);
            }
        });
    }

</script>

Yovo/Views/Houses/Details.cshtml
@model Yovo.Viewmodel.HouseSpecsViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    footer, hr {
        display: none!important;
    }
</style>

<div class="col-md-8" style="margin:0 auto; border-right: solid; border-radius: 10px; border-bottom: solid; box-shadow: 7px 10px 26px lightgrey; border-color: lightgrey;">
    <div class="col-md-6" style="float: left; ">

        @{
            var base64 = Convert.ToBase64String(Model.HouseImg.Image);
            var imgsrc = string.Format("data:image/gif;base64,{0}", base64);

        }

        <img src="@imgsrc"  />

    </div>
    <div class="col-md-6" style="float: left; border-right: solid; border-radius: 10px; border-bottom: solid; box-shadow: 7px 10px 26px lightgrey; border-color: lightgrey;">
        <div class="col-md-12"><p style="font-size: larger;border-bottom: 1px solid;">Ιδιοκτήτης: <strong>@Html.DisplayFor(model => model.House.Owner.FirstName) @Html.DisplayFor(model => model.House.Owner.LastName)</strong></p></div>
        <div class="col-md-12"><p style="font-size: larger;border-bottom: 1px solid;">Επισκέπτες: <strong>@Html.DisplayFor(model => model.House.Visitors)</strong></p></div>
        <div class="col-md-12"><p style="font-size: larger;border-bottom: 1px solid;">Τετραγωνικά: <strong>@Html.DisplayFor(model => model.House.SquareMeters)</strong></p></div>
        <div class="col-md-12"><p style="font-size: larger;border-bottom: 1px solid;">Δωμάτια: <strong>@Html.DisplayFor(model => model.House.Rooms)</strong></p></div>
        <div class="col-md-12"><p style="font-size: larger;border-bottom: 1px solid;"> Επιπλέον:<strong>
        
            @foreach (var item in Model.House.Features)
        {<br /> @Html.DisplayFor(modelItem => item.Description)}
    </strong>
</p></div>
        <div class="col-md-12"><p style="font-size: larger;border-bottom: 1px solid;">Περιγραφή: <strong> @Html.DisplayFor(model => model.House.Description)</strong></p></div>

        <p><strong></strong></p>
    </div>
    <div class="col-md-12">
        @if (ViewBag.UserId == Model.House.Owner.Id)
        {
            <div class="col-md-2 btn btn-outline-primary waves-effect" style="float:left; margin-right: 20px;">
                @Html.ActionLink("Availability", "Availability", "Reservations", new { houseId = Model.House.Id }, null)
            </div>
            <div class="col-md-2 btn btn-outline-primary waves-effect" style="float:left; margin-right: 20px;">
                @Html.ActionLink("House Bookings", "HouseReservations", "Reservations", new { id = Model.House.Id }, null)
            </div>
            <div class="col-md-2 btn btn-outline-primary waves-effect" style="float:left; margin-right: 20px;">
                @Html.ActionLink("Edit", "Edit", new { id = Model.House.Id })
            </div>
            <div class="col-md-2 btn btn-outline-danger waves-effect" style="float:left; margin-right: 20px;">
                @Html.ActionLink("Delete House", "Delete", new { id = Model.House.Id })
            </div>
        }
        else
        {
            <div class="col-md-2 btn btn-outline-success waves-effect" style="float:left; margin-right: 20px;">
                @Html.ActionLink("Book", "Book", "Reservations", new { houseId = Model.House.Id }, null)
            </div>
        }
        <div class="col-md-2 btn btn-outline-primary waves-effect" style="float: left; margin-right: 20px;">
            @Html.ActionLink("Back To List", "")
        </div>
    </div>
        </div>