Yovo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Yovo.Models;
using Yovo.Viewmodel;

namespace Yovo.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            SearchVM src = new SearchVM();
            src.Address = db.Addresses.Include(adrs=> adrs.House).ToList();
            src.House = db.Houses.Include(hss => hss.Owner).ToList();
            src.HouseImg = db.HouseImgs.ToList();


            //Loop for Price & SquareMeters Slides.
            decimal maxP = 0;
            decimal minP = 99999;
            decimal maxS = 0;
            decimal minS = 99999;
            foreach(var item in db.Houses)
            {
                if (item.Price > maxP)
                {
                    maxP = item.Price;
                    src.MaxPrice = item.Price;
                }
                if(item.Price < minP)
                {
                    minP = item.Price;
                    src.MinPrice = item.Price;
                }
                if (item.SquareMeters> maxS)
                {
                    maxS = item.SquareMeters;
                    src.Maxsqr= item.SquareMeters;
                }
                if (item.SquareMeters < minS)
                {
                    minS = item.SquareMeters;
                    src.Minsqr= item.SquareMeters;
                }

            }



            return View(src);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Yovo/Controllers/HousesController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Yovo.Models;
using Yovo.Viewmodel;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Web;
using System.Data.SqlClient;

namespace Yovo.Controllers
{
    public class HousesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Houses
        public ActionResult Index()
        {
            ViewBag.Owners = db.Users.Where(u => u.Roles.ToString() == "Owner");
            var x = db.Houses.Include(h => h.Owner).ToList();
            return View(db.Houses.Include(h => h.Owner));
        }



        [HttpGet]
        public ActionResult SearchResults(string region, string city, decimal? price, decimal? SquareMeters)
        {
            SearchVM src = new SearchVM();
            var userid = User.Identity.GetUserId();
            var query = db.Addresses.Include(adr => adr.House).Include(adr => adr.House.Owner).Where(adr => adr.House.Owner.Id != userid);
            var x = query.ToList();
            if (region != "0"){query = query.Where(adr => adr.Region == region);}

            if (city != "0"){query = query.Where(adr => adr.Country == city);}

            if (price != null){query = query.Where(adr => adr.House.Price == price);}

            if (SquareMeters != null){query = query.Where(adr => adr.House.SquareMeters == SquareMeters);}
                       
            src.Address = query.ToList();
            src.HouseImg = db.HouseImgs.ToList();
            return View(src);
        }


        // GET: Houses
        public ActionResult MyHouses()
        {
            var CurrentUser = User.Identity.GetUserId();
            var houses = new SearchVM();
            houses.House = db.Houses.Include(h => h.Features).Where(h => h.Owner.Id == CurrentUser).ToList();
            houses.HouseImg = db.HouseImgs.ToList();
            //var CurrentUserId = ac.UserManager.FindById(User.Identity.GetUserId());
            return View(houses);
        }

        // GET: Houses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // Because it is an array of bits we need to instantiate it before to save it.
            HouseSpecsViewModel house = new HouseSpecsViewModel();
            house.House = db.Houses.Include(h => h.Owner).Include(h => h.Features).SingleOrDefault(h => h.Id == id);
            house.Address = db.Addresses.SingleOrDefault(a => a.HouseId == id);
            house.HouseImg = db.HouseImgs.SingleOrDefault(i => i.HouseId == id);

            ViewBag.UserId = User.Identity.GetUserId();
            if (house == null)
            {
                return HttpNotFound();
            }
            var x = house;
            return View(house);
        }

        // GET: Houses/Create
        public ActionResult Create()
        {
            HouseSpecsViewModel h = new HouseSpecsViewModel();
            h.Features = db.Features.ToList();
            h.HouseImg = new HouseImg();
            return View(h);
        }

        // POST: Houses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HouseSpecsViewModel model, HttpPostedFileBase image1)
        {
            var x = image1;
            if (ModelState.IsValid)
            {
                var y = Request.Files[0];
                House house = model.House;
                Address address = model.Address;
                foreach (var item in model.Features)
                {
                    if (item.IsChecked)
                    {
                        house.Features.Add(db.Features.Find(item.Id));
                        item.IsChecked = false;
                    }
                }
                if (image1 != null)
                {
                    model.HouseImg = new HouseImg();
                    model.HouseImg.Image = new byte[image1.ContentLength];
                    image1.InputStream.Read(model.HouseImg.Image, 0, image1.ContentLength);
                    model.HouseImg.HouseId = model.House.Id;
                    db.HouseImgs.Add(model.HouseImg);
                }

                house.Owner = db.Users.Find(User.Identity.GetUserId());
                address.HouseId = house.Id;
                db.Houses.Add(house);
                db.Addresses.Add(address);
                db.SaveChanges();
              

                var ctrl = new AccountController();
                ctrl.ControllerContext = ControllerContext;
                var test = User.Identity.GetUserId();
                ctrl.UserManager.RemoveFromRole(User.Identity.GetUserId(), "Renter");
                ctrl.UserManager.AddToRole(User.Identity.GetUserId(), "Owner");
                return RedirectToAction("Index");
            }

            return RedirectToAction("Details", new { id = model.House.Id});
        }

        // GET: Houses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            House house = db.Houses.Find(id);
            if (house == null)
            {
                return HttpNotFound();
            }
            return View(house);
        }

        // POST: Houses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Description,Rooms,Visitors,SquareMeters,Price,UserId")] House house)
        {
            if (ModelState.IsValid)
            {
                db.Entry(house).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(house);
        }

        // GET: Houses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            House house = db.Houses.Find(id);
            if (house == null)
            {
                return HttpNotFound();
            }
            return View(house);
        }

        // POST: Houses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            House house = db.Houses.Find(id);
            db.Houses.Remove(house);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Yovo/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title</h2>
<h3>Yovo Project by Team 3 .NET Academy (aka Thundercats)</h3>

<p>This website is made as a project in the .net academy in order to learn .net technologies and mvc techniques.</p>
<p>For more information @Html.ActionLink("Contact Us", "Contact").</p>

<h5>Thank you for your attention!</h5>

Yovo/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title Us</h2>
<h3>And we are</h3>

<ul>
    <li><p>Balas Georgios <a href="mailto:gbalas07@gmail.com">gbalas07@gmail.com</a></p></li>
    <li><p>Digalakis Theodoros <a href="mailto:elmichai91@gmail.com">elmichai91@gmail.com</a></p></li>
    <li><p>Mihailidis Eleftherios <a href="mailto:th.digalakis@gmail.com">th.digalakis@gmail.com</a></p></li>
    </ul>

Yovo/Views/Home/Index.cshtml
@model Yovo.Viewmodel.SearchVM

@{
    ViewBag.Title = "Home Page";
}

<script>



//Script for Bing Maps START
    var map, infobox;
    function GetMap()
    {

        map = new Microsoft.Maps.Map('#myMap', {
            center: new Microsoft.Maps.Location(39.305035, 24.029026),
            zoom: 6,
            disableScrollWheelZoom: true
        });

        //Create an infobox at the center of the map but don't show it.
        infobox = new Microsoft.Maps.Infobox(map.getCenter(), {
            visible: false
        });

        //Assign the infobox to a map instance.
        infobox.setMap(map);

        //Create random locations in the map bounds.
        /*var randomLocations = Microsoft.Maps.TestDataGenerator.getLocations(5, map.getBounds());*/

        var pushPins = new Array(@Model.Address.Count());
        var counter = 0;
        var houseArray = [];
        @foreach (var item in Model.Address)
        {

            <text>

            pushPins[counter] = {
                'lat': @Convert.ToDouble(item.Latitude),
                'lng': @Convert.ToDouble(item.Longitude) };


        houseArray[counter] = {'title':  "@(item.House.Title)", 'region' : "@(item.Region)" ,'descr': "@(item.House.Description)" } ;
            counter = counter + 1;
            </text>
        }
        var locations = [];
        for (var i = 0; i < pushPins.length; i++) {
            locations[i] = new Microsoft.Maps.Location(pushPins[i].lat, pushPins[i].lng);
            var pin = new Microsoft.Maps.Pushpin(locations[i]);

            //Store some metadata with the pushpin.
            pin.metadata = {
                title: houseArray[i].title,
                region: houseArray[i].region,
                description: houseArray[i].descr
            };

            //Add a click event handler to the pushpin.
            Microsoft.Maps.Events.addHandler(pin, 'click', pushpinClicked);
            
            //Add pushpin to the map.
            map.entities.push(pin);
        }

    }

    function pushpinClicked(e) {
        //Make sure the infobox has metadata to display.
        if (e.target.metadata) {
            //Set the infobox options with the metadata of the pushpin.
            infobox.setOptions({
                location: e.target.getLocation(),
                title: e.target.metadata.title,
                description: e.target.metadata.description,
                visible: true
            });
        }
    }

//Script for Bing Maps END

</script>
<script type='text/javascript' src='http://www.bing.com/api/maps/mapcontrol?callback=GetMap&key=AjtUzWJBHlI3Ma_Ke6Qv2fGRXEs0ua5hUQi54ECwfXTiWsitll4AkETZDihjcfeI' async defer></script>

@{ bool areSame = false;}

<body onload="animate();">
    <div class="welcome-area wow fadeInUp" data-wow-delay="200ms">
        <div id="myMap" style="position:relative;width:100%;height:100%;float:left"></div>
    </div>
    <div class="rehomes-search-form-area wow fadeInUp" data-wow-delay="200ms">
        <div class="container">
            <div class="rehomes-search-form">
                @using (Html.BeginForm("SearchResults", "Houses", FormMethod.Get))
                {
                    <div class="row">
                        <div class="col-12 col-lg-10">
                            <div class="row">
                                <div class="col-12 col-md-6 col-lg-3">
                                    <select name="city" id="city" class="form-control">
                                        <option value="0">City</option>
                                        @for (var i = 0; i < Model.Address.Count; i++)
                                        {
                                            for (var y = 0; y < i; y++)
                                            {
                                                if (Model.Address[y].Country == Model.Address[i].Country)
                                                {
                                                    areSame = true;
                                                }
                                            }
                                            if (!areSame)
                                            {
                                                <option value="@Model.Address[i].Country" >@Model.Address[i].Country</option>
                                            }

                                        }
                                    </select>
                                </div>
                                <div class="col-12 col-md-6 col-lg-3" >
                                    <select name="region" id="region" class="form-control">
                                        <option value="0" id="regionoption">Region</option>
                                    </select>
                                </div>
                                <div class="col-12 col-md-6 col-lg-3">
                                    @Html.TextBox("Rooms", null, new { @class = "form-control", @type = "number", @placeholder = "Rooms", @min = 1, @name = "Rooms" })
                                </div>

                                <div class="col-12 col-md-6 col-lg-3">
                                    <div class="slider-range mb-15">
                                        <div class="range-price text-white">Price [@Model.MinPrice - @Model.MaxPrice]$</div>
                                        <div name="price" id="price" class="slider-range-price ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" data-min="@Convert.ToInt32(Model.MinPrice)" data-max="@Convert.ToInt32(Model.MaxPrice)" data-unit="$" data-value-min="@Model.MinPrice" data-value-max="@Model.MaxPrice" data-label-result="Price">
                                            <div class="ui-slider-range ui-widget-header ui-corner-all"></div>
                                            <span class="ui-slider-handle ui-state-default ui-corner-all" tabindex="0"></span>
                                            <span class="ui-slider-handle ui-state-default ui-corner-all" tabindex="0"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12 col-md-6 col-lg-3">
                                    <div class="slider-range mb-15">
                                        <div class="range-size text-white">Size [@Model.Minsqr - @Model.Maxsqr]sqFt</div>
                                        <div name="SquareMeters" data-min="@Convert.ToInt32(Model.Minsqr)" data-max="@Convert.ToInt32(Model.Maxsqr)" data-unit="sqFt" class="slider-range-size ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" data-value-min="@Convert.ToInt32(Model.Minsqr)" data-value-max="@Convert.ToInt32(Model.Maxsqr)" data-label-result="Size">
                                            <div class="ui-slider-range ui-widget-header ui-corner-all"></div>
                                            <span class="ui-slider-handle ui-state-default ui-corner-all" tabindex="0"></span>
                                            <span class="ui-slider-handle ui-state-default ui-corner-all" tabindex="0"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-lg-2">
                            <button type="submit" class="btn rehomes-search-btn">Search</button>
                            <!--Html.ActionLink("Search", "SearchResults", "Houses", new { search = region }, null)-->
                        </div>
                    </div>
                }
            </div>


        </div>
    </div>
    <!-- **** Sale area Start **** -->
    <section class="rehome-house-sale-area section-padding-100-60">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section-heading text-center wow fadeInUp" data-wow-delay="200ms">
                        <h2>Top New In <span>Greece</span></h2>
                        <p>These are the best deals and deals. All in Greece</p>
                    </div>
                </div>

                <!-- Single Property Area -->
                @foreach (var house in Model.House)
                {

                    <div class="col-12 col-md-6 col-lg-3">
                        <div class="single-property-area wow fadeInUp" data-wow-delay="200ms">
                            <!-- Property Thumb -->
                            <div class="property-thumb">
                                @{
                                    var base64 = Convert.ToBase64String(Model.HouseImg.FirstOrDefault(img => img.HouseId == house.Id).Image);
                                    var imgsrc = string.Format("data:image/gif;base64,{0}", base64);

                                }
                                <img src="@imgsrc" style="max-height: 200px; height: 100%" />
                            </div>
                            <!-- Property Description -->
                            <div class="property-desc-area">
                                <!-- Property Title & Seller -->
                                <div class="property-title-seller d-flex justify-content-between">
                                    <!-- Title -->
                                    <div class="property-title">
                                        <h4>@Model.Address.FirstOrDefault(adr => adr.HouseId == house.Id).Country</h4>
                                        <p><i class="fa fa-map-marker" aria-hidden="true"></i>@Model.Address.FirstOrDefault(adr => adr.HouseId == house.Id).Region</p>
                                    </div>
                                    <!-- Seller -->
                                    <div class="property-seller">
                                        <p>Seller:</p>
                                        <h6>@Model.Address.FirstOrDefault(adr => adr.HouseId == house.Id).House.Owner.LastName</h6>
                                    </div>
                                </div>
                                <!-- Property Info -->
                                <div class="property-info-area d-flex flex-wrap">
                                    <p>Sqft: <span>@Model.Address.FirstOrDefault(adr => adr.HouseId == house.Id).House.SquareMeters</span></p>
                                    <p>Rooms: <span>@Model.Address.FirstOrDefault(adr => adr.HouseId == house.Id).House.Rooms</span></p>
                                    <p>Visitors: <span>@Model.Address.FirstOrDefault(adr => adr.HouseId == house.Id).House.Visitors</span></p>
                                </div>
                            </div>

                            <!-- Property Price -->
                            <div class="property-price">

                                <p class="badge-sale"><a href="Houses/Details/@house.Id">For Rent</a></p>
                                <p class="price">€ @Model.Address.FirstOrDefault(adr => adr.HouseId == house.Id).House.Price /per Day</p>
                            </div>
                        </div>
                    </div>
                }


            </div>
        </div>
    </section>
    <!-- **** Sale Area End **** -->
</body>
@*<script src="~/Scripts/jquery.min.js"></script>*@
<script>
    var city = document.getElementById("city");
    var select2 = document.getElementById("region");
        var regions = [];
        
    city.onchange = function () {
        var counter = 0;
        var len = select2.options.length;
        for (var i = 1; i < len; i++) {
            select2.options[1].remove();
        }
        @foreach(var adr in Model.Address)
        {
            <Text>
            if ("@(adr.Country)" == city.value) {
                regions[counter] = { 'reg' : "@(adr.Region)"} ;
                counter++;
            }
        </Text>
        }
            for (var i = 0; i < counter; i++) {
                var o = document.createElement("option");
                o.value = regions[i].reg;   
                o.text = regions[i].reg;
                select2.add(o);
        }

        select2.style.display = "inline";
        }
</script>